# Generated by Django 5.2.5 on 2025-08-27 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_is_active_item_is_rentable_item_is_sellable_and_more'),
        ('rentals', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='returned_at',
            new_name='returned_date',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='rented_at',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='item',
        ),
        migrations.AddField(
            model_name='rental',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rental',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='stores.store'),
        ),
        migrations.AddField(
            model_name='rental',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returned_qty', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_items', to='inventory.item')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('damage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_reports', to='rentals.rentalitem')),
            ],
        ),
    ]
